// ─── 2 ───
# Your code here
for _ in range(100):
    print("Khul Ja Sim Sim!")
    

// ─── 5 ───
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!
Khul Ja Sim Sim!